// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ArcCommander")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","09.11.2023")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ArcCommander"
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "09.11.2023"
