// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ArcCommander")>]
[<assembly: AssemblyVersionAttribute("0.5.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","12.04.2023")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ArcCommander"
    let [<Literal>] AssemblyVersion = "0.5.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "12.04.2023"
