// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SWATE")>]
[<assembly: AssemblyVersionAttribute("0.4.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","03.01.2023")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SWATE"
    let [<Literal>] AssemblyVersion = "0.4.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "03.01.2023"
