// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ArcCommander")>]
[<assembly: AssemblyProductAttribute("ArcCommander")>]
[<assembly: AssemblyDescriptionAttribute("FSharp Library")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ArcCommander"
    let [<Literal>] AssemblyProduct = "ArcCommander"
    let [<Literal>] AssemblyDescription = "FSharp Library"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
